version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
