version: "3.7"
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    user: root
