version: "3.9"
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./pg-data/:/var/lib/postgresql/data
    user: root
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
